owner: zesty-co
repo: status

sites:
  - name: Website
    url: https://zesty.co
    icon: https://zesty.co/wp-content/uploads/2020/12/cropped-zesty_favicon-2-120x120.png
    maxResponseTime: 1000
  - name: Dashboard
    url: $ZESTY_APP
    maxResponseTime: 1000
  - name: API
    url: $ZESTY_API
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
      - 403

status-website:
  cname: status.zesty.co
  logoUrl: https://app.zesty.co/assets/logo/zesty-logo.svg
  favicon: https://zesty.co/wp-content/uploads/2020/12/cropped-zesty_favicon-2-120x120.png
  name: Zesty Status
  introTitle: ""
  introMessage: ""
  css: "p { display: none; }"
  navbar:
    - title: Status
      href: /
    - title: Zesty
      href: https://zesty.co
